Fix/models
FundIngSoft2021-10/phoenixWear pull request #12
Opened 2021-04-01 05:18 UTC by CarlosAndresErazoGarzon

# Descripción

## Tipo de cambio

- [] Corrección de errores (cambio permanente que soluciona un problema)

2021-04-02 23:53 UTC, monotera requested changes
Me gustó mucho como lo trabajaste 💯 , solo te hice un pequeño comentario

2021-04-02 23:53 UTC, monotera commented on server/controllers/products.js
> +exports.postAProduct = async (req, res) => {
Viendo que hay varios métodos get, seria bueno si todos los métodos get estuvieran en un archivo, los post en otro, los put en otro y los delete en otro.

2021-04-02 23:53 UTC, monotera commented on server/controllers/records.js
> +exports.post = async (req, res) => {
Lo mismo del arriba

2021-04-03 00:56 UTC, CarlosAndresErazoGarzon commented on server/controllers/records.js
> +exports.post = async (req, res) => {
Listo, ya quedaron separados y verifiqué que todo quedará correctamente

2021-04-03 01:01 UTC, monotera approved these changes
https://i.pinimg.com/736x/13/ff/49/13ff49773ca9c25ac2116c8bc6c4d2ee.jpg

2021-04-03 01:01 UTC, merged